### ISSUE TITLE
Model fit section 7.3.2

### ISSUE THREAD

**Issue by amandawarlick** [nwfsc-timeseries/atsa-labs#4]
I'm still at the beginning stages of working my way through the homework/lab, but one question - in section 7.3.2 Model Fitting for harbor seals as one big population, it says 'the model fits fine', but I'm not sure I'm understanding how we're gauging that based on MARSS() output. Is it the 'Success!' message? What would it look like if the model fit poorly or didn't converge?

**Comment by eeholmes** [comment]
'fits fine' just means that the model converged.  There is a maximum in the likelihood surface and the algorithm found it.  As you will see however when you examine the residuals, this is a poor model.  The model residuals have trends and autocorrelation.

`fits poorly` can mean a number of different things.  1) is what is meant in the text while 2) and 3) relate more to the suitability of the model for the data at hand.

1. The model won't converge.  This could be because the likelihood surface has ridges indicating many parameter values that can fit the data equally well (well=same likelihood).  Or it could be that you have specified a model that is confounded.  Example would a model with two parameters that do exactly the same thing.  Like two intercepts in a linear regression.

2. The residuals are not stationary. They have trends and autocorrelation.  This indicates that the model is insufficient to explain the structure in the data.

3. In a model selection context where you are fitting multiple models, you might say one 'fits poorly' if it's AIC (or AICc or BIC or cross-validation metric) is much worse than other models in your set.  Technically, this is not 'fitting poorly'.

**Comment by amandawarlick** [comment]
Okay, thanks - makes sense. I think I was also particularly curious about how we were gauging the fit/convergence based on the marrs() output particularly when we're not comparing AIC values, but I think in this case we were just looking at the residuals and making conclusions from that. Thanks!
